apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv

spec:
  storageClassName: ""
  hostPath:
    path: /media/omri/Shared/projects/k8s-tutorial/volumes/pv
  capacity:
    storage: 0.5Gi
  accessModes:
  - ReadWriteMany
  claimRef:
    name: mongodb-pvc

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc

spec:
  storageClassName: ""
  volumeName: mongodb-pv
  resources:
    requests:
      storage: 0.5Gi
  accessModes:
  - ReadWriteMany
