apiVersion: apps/v1
kind: Deployment

metadata:
  name: simple-node-deployment
  
  labels:
   app: simple-node

spec:
  replicas: 2
  selector:
   matchLabels:
    app: simple-node

  template:
    metadata:
      labels:
        app: simple-node

    spec:
      containers:
      - name: simple-node
        image: simple-node:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name